### ISSUE TITLE
Gnome 47 compatibility

### ISSUE THREAD

**Issue by drakkar1969** [Extensions-Valhalla/gnome-bluetooth-quick-connect#14]
Thanks for the great extension, would be great if it could be updated for Gnome 47

**Comment by BlankParticle** [comment]
Sorry, I don't have a Gnome setup anymore to test out stuff, still I will look into this and update the extension

**Comment by BlankParticle** [comment]
ref #15

**Comment by drakkar1969** [comment]
Thanks, working perfectly with version 51
