### ISSUE TITLE
this._logger is null error shown

### ISSUE THREAD

**Issue by aral** [Extensions-Valhalla/gnome-bluetooth-quick-connect#2]
On Fedora Silverblue 39 with GNOME 45.

**Comment by BlankParticle** [comment]
I am have already fixed the issue, I am pushing a new version to EGO right now, it may take some time to get it reviewed.

Here is a build for that fix to use until it gets review:
[bluetooth-quick-connect@bjarosze.gmail.com.shell-extension.zip](https://github.com/Extensions-Valhalla/gnome-bluetooth-quick-connect/files/13308342/bluetooth-quick-connect%40bjarosze.gmail.com.shell-extension.zip)

**Comment by aral** [comment]
Thanks so much :)

**Comment by BlankParticle** [comment]
Fixed version is now live on extensions.gnome.org, closing thus issue as completed.
