### ISSUE TITLE
Extension is only visible when Bluetooth is already turned on.

### ISSUE THREAD

**Issue by Northguy** [Extensions-Valhalla/gnome-bluetooth-quick-connect#4]
Tried using the extension on Pop!OS. The extension is visible when Bluetooth is turned on and can then be used to enter Bluetooth settings, or turn the Bluetooth off, but once Bluetooth is turned off, the extension disappears: it is not possible to use the extension to re-enable the Bluetooth. For this I need to enter the original settings menu and enable bluetooth from there. Once enabled there, the extension becomes visible again.

It would be very convenient when the bluetooth extension is always visible

If more detailed debug info is required, please specify (and how to obtain).

**Comment by BlankParticle** [comment]
Hello, thanks for reporting.
Can you provide some screenshot of what do you want to mean?

I work with Gnome 45 and enabling/disabling Bluetooth can be done from quick settings panel. I am not sure how it's over at PopOS.

**Comment by Northguy** [comment]
Hi @BlankParticle have a look at video contained in attached ZIP. A video says more than 1000 screenshots ;-)

[simplescreenrecorder-2023-11-11_19.45.41.zip](https://github.com/Extensions-Valhalla/gnome-bluetooth-quick-connect/files/13326249/simplescreenrecorder-2023-11-11_19.45.41.zip)

**Comment by BlankParticle** [comment]
I am pretty sure that turn off button is not provided by the extension but provided by Pop!OS itself.
Does this happen only when the extension is installed?

**Comment by Northguy** [comment]
When the extension is not installed, there is no way to change bluetooth settings in the quick panel, then I always need to go through the ' generic' settings to enable/disable. Therefore this extension is helpful, but only if it persistent (also when bluetooth is off)

**Comment by BlankParticle** [comment]
Ok, I will boot up Pop!Os in vm to check on stuff probably tomorrow, until then please provide your system config. Like the version of the extension, gnome version, distro, etc.

A default neofetch would be enough to get the general idea. We can go into specific details if I can't replicate the issue. Also check with version of the extension you are running.

**Comment by Northguy** [comment]
Hi,

I installed the latest available extension from the website.

<pre>$ neofetch
<font color="#06989A"><b>             /////////////</b></font>                <font color="#06989A"><b>northguy</b></font>@<font color="#06989A"><b>SurfacePro3</b></font> 
<font color="#06989A"><b>         /////////////////////</b></font>            ------------------- 
<font color="#06989A"><b>      ///////</b></font><b>*767</b><font color="#06989A"><b>////////////////</b></font>         <font color="#06989A"><b>OS</b></font>: Pop!_OS 22.04 LTS x86_64 
<font color="#06989A"><b>    //////</b></font><b>7676767676*</b><font color="#06989A"><b>//////////////</b></font>       <font color="#06989A"><b>Host</b></font>: Surface Pro 3 1 
<font color="#06989A"><b>   /////</b></font><b>76767</b><font color="#06989A"><b>//</b></font><b>7676767</b><font color="#06989A"><b>//////////////</b></font>      <font color="#06989A"><b>Kernel</b></font>: 6.5.6-76060506-generic 
<font color="#06989A"><b>  /////</b></font><b>767676</b><font color="#06989A"><b>///</b></font><b>*76767</b><font color="#06989A"><b>///////////////</b></font>     <font color="#06989A"><b>Uptime</b></font>: 9 mins 
<font color="#06989A"><b> ///////</b></font><b>767676</b><font color="#06989A"><b>///</b></font><b>76767</b><font color="#06989A"><b>.///</b></font><b>7676*</b><font color="#06989A"><b>///////</b></font>    <font color="#06989A"><b>Packages</b></font>: 1927 (dpkg), 19 (flatpak), 11 (snap) 
<font color="#06989A"><b>/////////</b></font><b>767676</b><font color="#06989A"><b>//</b></font><b>76767</b><font color="#06989A"><b>///</b></font><b>767676</b><font color="#06989A"><b>////////</b></font>   <font color="#06989A"><b>Shell</b></font>: bash 5.1.16 
<font color="#06989A"><b>//////////</b></font><b>76767676767</b><font color="#06989A"><b>////</b></font><b>76767</b><font color="#06989A"><b>/////////</b></font>   <font color="#06989A"><b>Resolution</b></font>: 2160x1440 
<font color="#06989A"><b>///////////</b></font><b>76767676</b><font color="#06989A"><b>//////</b></font><b>7676</b><font color="#06989A"><b>//////////</b></font>   <font color="#06989A"><b>DE</b></font>: GNOME 42.5 
<font color="#06989A"><b>////////////,</b></font><b>7676</b><font color="#06989A"><b>,///////</b></font><b>767</b><font color="#06989A"><b>///////////</b></font>   <font color="#06989A"><b>WM</b></font>: Mutter 
<font color="#06989A"><b>/////////////*</b></font><b>7676</b><font color="#06989A"><b>///////</b></font><b>76</b><font color="#06989A"><b>////////////</b></font>   <font color="#06989A"><b>WM Theme</b></font>: Pop 
<font color="#06989A"><b>///////////////</b></font><b>7676</b><font color="#06989A"><b>////////////////////</b></font>   <font color="#06989A"><b>Theme</b></font>: Pop-dark [GTK2/3] 
<font color="#06989A"><b> ///////////////</b></font><b>7676</b><font color="#06989A"><b>///</b></font><b>767</b><font color="#06989A"><b>////////////</b></font>    <font color="#06989A"><b>Icons</b></font>: Pop [GTK2/3] 
<font color="#06989A"><b>  //////////////////////</b></font><b>&apos;</b><font color="#06989A"><b>////////////</b></font>     <font color="#06989A"><b>Terminal</b></font>: gnome-terminal 
<font color="#06989A"><b>   //////</b></font><b>.7676767676767676767,</b><font color="#06989A"><b>//////</b></font>      <font color="#06989A"><b>CPU</b></font>: Intel i3-4020Y (4) @ 1.500GHz 
<font color="#06989A"><b>    /////</b></font><b>767676767676767676767</b><font color="#06989A"><b>/////</b></font>       <font color="#06989A"><b>GPU</b></font>: Intel Device 0a1e 
<font color="#06989A"><b>      ///////////////////////////</b></font>         <font color="#06989A"><b>Memory</b></font>: 2105MiB / 3812MiB 
<font color="#06989A"><b>         /////////////////////</b></font>
<font color="#06989A"><b>             /////////////</b></font>                <span style="background-color:#333333"><font color="#333333">   </font></span><span style="background-color:#CC0000"><font color="#CC0000">   </font></span><span style="background-color:#4E9A06"><font color="#4E9A06">   </font></span><span style="background-color:#C4A000"><font color="#C4A000">   </font></span><span style="background-color:#3465A4"><font color="#3465A4">   </font></span><span style="background-color:#75507B"><font color="#75507B">   </font></span><span style="background-color:#06989A"><font color="#06989A">   </font></span><span style="background-color:#D3D7CF"><font color="#D3D7CF">   </font></span>
                                          <span style="background-color:#88807C"><font color="#88807C">   </font></span><span style="background-color:#F15D22"><font color="#F15D22">   </font></span><span style="background-color:#73C48F"><font color="#73C48F">   </font></span><span style="background-color:#FFCE51"><font color="#FFCE51">   </font></span><span style="background-color:#48B9C7"><font color="#48B9C7">   </font></span><span style="background-color:#AD7FA8"><font color="#AD7FA8">   </font></span><span style="background-color:#34E2E2"><font color="#34E2E2">   </font></span><span style="background-color:#EEEEEC"><font color="#EEEEEC">   </font></span>

</pre>

**Comment by BlankParticle** [comment]
[Screencast from 2023-11-12 13-05-27.webm](https://github.com/Extensions-Valhalla/gnome-bluetooth-quick-connect/assets/130567419/f0a191b5-70c8-4b77-befd-27e8df97887e)

Hello, Is this what behaviour you wanted?

**Comment by Northguy** [comment]
That looks exactly like expected behaviour. I'll check out the troubleshooting guide. I'll consider this issue closed. Thanks for the effort.
