### ISSUE TITLE
It quit working a few daya ago...

### ISSUE THREAD

**Issue by mcoyle1960** [Extensions-Valhalla/gnome-bluetooth-quick-connect#6]
I use this daily, and a few days ago it quit. The extension still loads, but there are no devices listed, in fact there is no dropdown menu at all. It acts as if it's not even installed. 

And it happened on two partitions. I have Fedora 39 as my daily driver, and a Fedora Rawhide partition for testing. 

If I were to guess, it was either Friday the 15th or Saturday the 16th when it quit. Let me know what additional info you may need.

-----------------------------------------------------
OS: Fedora Linux 39 (Workstation Edition) x86_64
Host: 81LL IdeaPad L340-17IRH Gaming 
Kernel: 6.6.6-200.fc39.x86_64 
Resolution: 1920x1080 
DE: GNOME 45.2 
WM: Mutter 
WM Theme: Adwaita 
Terminal: gnome-terminal 
CPU: Intel i7-9750H (12) @ 2.6GHz [64.0°on] 
GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q 
GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630] 
Memory: 2442MiB / 31962MiB (7%)

**Comment by BlankParticle** [comment]
Hello,
You can try uninstalling and then reinstalling the extension.
If that doesn't work go to extension settings, enable debug mode. Then restart, login and try opening the Bluetooth menu. 
Then obtain the logs with 
```bash
journalctl -xfe | grep gnome-shell > logs.txt
```
Send the `logs.txt` file here

**Comment by mcoyle1960** [comment]
I did what you asked and looked at the log file. I noticed a lot of theme errors THEN I remembered I changed my theme over the weekend and sure enough... the gtk4 theme was the problem. I'm using another theme and will let the author of the problematic one know of the issue. 

Thanks for all you work!

**Comment by BlankParticle** [comment]
Hey, did that Fix your extension?
Theme errors are totally normal and most likely they have nothing to do with the extension

**Comment by mcoyle1960** [comment]
Yes, a theme change fixed the extension. I switched between several themes and one clearly broke the extension. Would you still like the log?

**Comment by BlankParticle** [comment]
Yeah, the logs would help in investigation. As normally themes shouldn't break extensions. This is am interesting case

**Comment by mcoyle1960** [comment]
Here's a link from my NextCloud.

https://www.jennaudio.com/nextcloud/index.php/s/3ZZRexEA9BLM3JJ

**Comment by BlankParticle** [comment]
These logs have no error that indicates that the extension breaks at any point. Anyways, I am glad its fixed.
